### ISSUE TITLE
Module stuck at "loading word of the day..."

### ISSUE THREAD

**Issue by seattlecajun** [SVendittelli/MMM-wordnik#3]
Hi there, I've followed the instructions in the readme, and also the recommendations in the previous reported issue thread about running `npm install python-shell` and `sudo pip install wordnik` in the /MagicMirror location, all without luck.

I've got the API key from wordnik setup in the config.js folder as below:

{	
	module: "MMM-wordnik",
		position: "lower_third",
		config: {
			apikey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		}	
	},

I really like the idea of having a 'word of the day' and would love to get this module working. Any help is greatly appreciated. I've also looked into my profile settings on the wordnik website and made sure that 'word of the day' was enabled.

**Comment by Peakapot** [comment]
Same problem here.

`Running wordOfTheDay.py
Whoops! There was an uncaught exception...
TypeError: PythonShell is not a constructor
    at Class.runPython (/home/pi/MagicMirror/modules/MMM-wordnik/node_helper.js:25:23)
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-wordnik/node_helper.js:17:9)
    at Socket.<anonymous> (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:113:11)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:528:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)`

**Comment by GobleSt** [comment]
I pulled the update to master but still stuck at "Loading..."

**Comment by Alexgutniak** [comment]
Getting the same issue, stuck on loading...

**Comment by benjf** [comment]
A couple things which may help:

1. try `sudo pip3 install wordnik-py3`
2. if you then get a date parse error - https://github.com/wordnik/wordnik-python3/issues/4

**Comment by jimbroze** [comment]
@ #6 I think my latest commit may fix this. The pronunciation request url was incorrect and was giving a Http error.

**Comment by GobleSt** [comment]
Fresh wordnik install on my newest mirror and still stuck at loading...

**Comment by jimbroze** [comment]
> 
> 
> Fresh wordnik install on my newest mirror and still stuck at loading...

That's because I don't own this repo and my commit hasn't been merged. Only @SVendittelli can do that.

See #6 .

**Comment by GobleSt** [comment]
I added your change...

**Comment by jimbroze** [comment]
Oh. That's interesting, it worked for me. What error does MagicMirror give?

**Comment by GobleSt** [comment]
Actually, I put this on the back burner and did not troubleshoot.  I was hit with this Buster requiring a GUI password issue and rebuilt from scratch (and still have the wordnik loading issue).  Now I still have both of those issues AND intermittent wireless dropping issue (yes, power mgmt is off).

**Comment by GobleSt** [comment]
> Oh. That's interesting, it worked for me. What error does MagicMirror give?

In the /home/pi/.pm2/logs/MagicMirror-error.log I see this:
[2020-05-06 14:13:57.363] [ERROR]  SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at PythonShell.asJson (/home/pi/MagicMirror/node_modules/python-shell/index.js:383:21)
    at /home/pi/MagicMirror/node_modules/python-shell/index.js:325:42
    at Array.forEach (<anonymous>)
    at PythonShell.receiveInternal (/home/pi/MagicMirror/node_modules/python-shell/index.js:321:15)
    at PythonShell.receiveStderr (/home/pi/MagicMirror/node_modules/python-shell/index.js:305:21)
    at Socket.emit (events.js:205:15)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:271:13)
    at Socket.Readable.push (_stream_readable.js:210:10)
[2020-05-06 14:13:57.434] [ERROR]  PythonShellError: process exited with code 1
    at terminateIfNeeded (/home/pi/MagicMirror/node_modules/python-shell/index.js:144:27)
    at ChildProcess.<anonymous> (/home/pi/MagicMirror/node_modules/python-shell/index.js:133:13)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12) {
  executable: 'python3',
  options: null,
  script: 'modules/MMM-wordnik/wordOfTheDay.py',
  args: [ 'myapiishere' ],
  exitCode: 1

Where else should I look?

Thanks!
